let gamesData = [
    {
        image: "assets/boxArt/haloInfinite.jpeg",
        title: "Halo Infinite",
        publisher: "assets/xboxGameStudios.png",
        publisherText: "Microsoft Xbox Game Studios",
        platform: ["assets/xboxSeriesXS.png", "assets/xboxOne.png", "assets/windows.png"],
        platformText: "XboxSeriesX/S, XboxOne, Windows",
        developer: "assets/343Industries.png",
        developerText: "343 Industries",
        genre: "First-person shooter",
        price: "$59.99",
        release: 2021,
        stars: 4.5,
        rating: "87%",
        description: "Dive into 'Halo Infinite,' the thrilling sci-fi adventure where you become the legendary Master Chief. With cutting-edge graphics and immersive gameplay, experience the next evolution of the iconic franchise."
    },
    {
        image: "assets/boxArt/breathOfTheWild.jpg",
        title: "The Legend of Zelda: Breath of the Wild",
        publisher: "assets/nintendo.png",
        publisherText: "Nintendo",
        platform: ["assets/switch.webp"],
        platformText: "Switch",
        developer: "assets/nintendoEPD.png",
        developerText: "Nintendo EPD",
        genre: "Open world",
        price: "$59.99",
        release: 2017,
        stars: 5,
        rating: "97%",
        description: "After 100 years, Link wakes up alone in a world he doesn't remember. The legendary hero must explore a vast and dangerous land and regain his memories before Hyrule is lost forever."        
    },
    {
        image: "assets/boxArt/theLastOfUs2.png",
        title: "The Last of Us Part II",
        publisher: "assets/sonyInteractive.png",
        publisherText: "Sony Interactive Entertainment",
        platform: ["assets/ps4.png", "assets/ps5.png"],
        platformText: "Playstation4, Playstation5",
        developer: "assets/naughtyDog.png",
        developerText: "Naughty Dog",
        genre: "Survival",
        price: "$59.99",
        release: 2022,
        stars: 4.5,
        rating: "93%",        
        description: "Experience the devasting physical and emotional consequences of Ellie's vengeance as you embark on a relentless pursuit of those who've wronged her."
    }
];