let gamesData = [
    {
        image: "assets/boxArt/theLastOfUs2.png",
        title: "The Last of Us Part II Remastered",
        publisher: "assets/sonyInteractive.png",
        publisherText: "Sony Interactive Entertainment",
        platform: ["assets/ps5.png"],
        platformText: "Playstation5",
        developer: "assets/naughtyDog.png",
        developerText: "Naughty Dog",
        genre: "Action-adventure",
        price: "44.99",
        release: 2024,
        stars: 4.5,
        rating: "93%",        
        description: "Experience the devasting physical and emotional consequences of Ellie's vengeance as you embark on a relentless pursuit of those who've wronged her."
    },
    {
        image: "assets/boxArt/superMarioBrosWonder.webp",
        title: "Super Mario Bros Wonder",
        publisher: "assets/nintendo.png",
        publisherText: "Nintendo",
        platform: ["assets/switch.webp"],
        platformText: "Switch",
        developer: "assets/nintendoEPD.png",
        developerText: "Nintendo EPD",
        genre: "Platform",
        price: "$54.99",
        release: 2023,
        stars: 4.5,
        rating: "92%",        
        description: "Jump into the unexpected with Mario. Classic Mario gameplay is turned on its head with the addition of Wonder Flowers in the Super Mario Bros Wonder game."
    },
    {
        image: "assets/boxArt/theLastOfUs1.jpg",
        title: "The Last of Us Part I",
        publisher: "assets/sonyInteractive.png",
        publisherText: "Sony Interactive Entertainment",
        platform: ["assets/ps5.png", "assets/windows.png"],
        platformText: "Playstation5, Windows",
        developer: "assets/naughtyDog.png",
        developerText: "Naughty Dog",
        genre: "Action-adventure",
        price: "$59.99",
        release: 2023,
        stars: 4.5,
        rating: "89%",        
        description: "In a ravaged civilization, Joel, a weary protagonist, is hired to smuggle 14-year-old Ellie out of a military quarantine zone. However, what starts as a small job soon transforms into a brutal cross-country journey."
    },
    {
        image: "assets/boxArt/forzaMotorsport.jpeg",
        title: "Forza Motorsport",
        publisher: "assets/xboxGameStudios.png",
        publisherText: "Microsoft Xbox Game Studios",
        platform: ["assets/xboxSeriesXS.png", "assets/windows.png"],
        platformText: "XboxSeriesX/S, Windows",
        developer: "assets/turn10.png",
        developerText: "Turn 10 Studios",
        genre: "Arcade Racing",
        price: "$49.99",
        release: 2023,
        stars: 4,
        rating: "84%",        
        description: "Get behind the wheel of the world's most iconic cars and compete in intense races. Race 500+ cars including modern race cars across 20 living environments featuring dynamic time-of-day weather."
    },
    {
        image: "assets/boxArt/forspoken.jpeg",
        title: "Forspoken",
        publisher: "assets/squareEnix.png",
        publisherText: "Square Enix",
        platform: ["assets/ps5.png", "assets/windows.png"],
        platformText: "Playstation5, Windows",
        developer: "assets/luminousProductions.png",
        developerText: "Luminous Productions",
        genre: "Action role-playing",
        price: "$19.99",
        release: 2023,
        stars: 3,
        rating: "64%",        
        description: "Mysteriously transported from New York City, Frey finds herself trapped in the land of Athia. A magical, sentient bracelet is inexplicably wrapped around her arm, and Frey discovers the ability to use magic to traverse the sprawling landscapes of Athia."
    },
    {
        image: "assets/boxArt/godOfWarRagnarok.jpeg",
        title: "God of War Ragnarok",
        publisher: "assets/sonyInteractive.png",
        publisherText: "Sony Interactive Entertainment",
        platform: ["assets/ps4.png", "assets/ps5.png"],
        platformText: "Playstation4, Playstation5",
        developer: "assets/santaMonicaStudio.png",
        developerText: "Santa Monica Studio",
        genre: "Action-adventure",
        price: "$59.99",
        release: 2022,
        stars: 4.5,
        rating: "94%",        
        description: "Embark on a mythic journey for answers before Ragnarök arrives in God of War Ragnarok. Embark on an epic and heartfelt journey as Kratos and Atreus struggle with holding on and letting go."
    },
    {
        image: "assets/boxArt/metroidDread.jpeg",
        title: "Metroid Dread",
        publisher: "assets/nintendo.png",
        publisherText: "Nintendo",
        platform: ["assets/switch.webp"],
        platformText: "Switch",
        developer: "assets/nintendoEPD.png",
        developerText: "Nintendo EPD",
        genre: "Action-adventure",
        price: "$44.99",
        release: 2021,
        stars: 4.5,
        rating: "88%",
        description: "Samus’ story continues after the events of the Metroid™ Fusion game when she descends upon planet ZDR to investigate a mysterious transmission sent to the Galactic Federation."        
    },
    {
        image: "assets/boxArt/haloInfinite.jpeg",
        title: "Halo Infinite",
        publisher: "assets/xboxGameStudios.png",
        publisherText: "Microsoft Xbox Game Studios",
        platform: ["assets/xboxSeriesXS.png", "assets/xboxOne.png", "assets/windows.png"],
        platformText: "XboxSeriesX/S, XboxOne, Windows",
        developer: "assets/343Industries.png",
        developerText: "343 Industries",
        genre: "First-person shooter",
        price: "$34.99",
        release: 2021,
        stars: 4.5,
        rating: "87%",
        description: "Dive into 'Halo Infinite,' the thrilling sci-fi adventure where you become the legendary Master Chief. With cutting-edge graphics and immersive gameplay, experience the next evolution of the iconic franchise."
    },
    {
        image: "assets/boxArt/lifeIsStrangeTC.jpeg",
        title: "Life is Strange: True Colors",
        publisher: "assets/squareEnix.png",
        publisherText: "Square Enix",
        platform: ["assets/switch.webp", "assets/ps4.png", "assets/ps5.png", "assets/windows.png", "assets/xboxOne.png", "assets/xboxSeriesXS.png"],
        platformText: "Switch, Playstation4, XboxOne, XboxSeriesX/S, Playstation5, Windows",
        developer: "assets/deckNine.png",
        developerText: "Deck Nine",
        genre: "Adventure",
        price: "$24.99",
        release: 2021,
        stars: 4,
        rating: "81%",        
        description: "Alex hides her supernatural ability to manipulate the emotions of others. When her brother dies in an accident, she embraces her volatile power to reveal dark secrets buried by the town."
    },
    {
        image: "assets/boxArt/oriAndTheWillOfTheWisps.jpeg",
        title: "Ori and the Will of the Wisps",
        publisher: "assets/xboxGameStudios.png",
        publisherText: "Microsoft Xbox Game Studios",
        platform: ["assets/windows.png", "assets/switch.webp", "assets/xboxSeriesXS.png", "assets/xboxOne.png"],
        platformText: "Switch, XboxOne, XboxSeriesX/S, Windows",
        developer: "assets/moonStudios.png",
        developerText: "Moon Studios",
        genre: "Platform-adventure",
        price: "$17.99",
        release: 2020,
        stars: 4.5,
        rating: "90%",        
        description: "Embark on an all-new adventure in a vast and exotic world where you'll encounter towering enemies and challenging puzzles on your quest to unravel Ori's true destiny."
    },
    {
        image: "assets/boxArt/breathOfTheWild.jpg",
        title: "The Legend of Zelda: Breath of the Wild",
        publisher: "assets/nintendo.png",
        publisherText: "Nintendo",
        platform: ["assets/switch.webp"],
        platformText: "Switch",
        developer: "assets/nintendoEPD.png",
        developerText: "Nintendo EPD",
        genre: "Action-adventure",
        price: "$44.99",
        release: 2017,
        stars: 5,
        rating: "97%",
        description: "After 100 years, Link wakes up alone in a world he doesn't remember. The legendary hero must explore a vast and dangerous land and regain his memories before Hyrule is lost forever."        
    },
    {
        image: "assets/boxArt/unchartedLostLegacy.jpeg",
        title: "Uncharted: The Lost Legacy",
        publisher: "assets/sonyInteractive.png",
        publisherText: "Sony Interactive Entertainment",
        platform: ["assets/ps4.png", "assets/ps5.png", "assets/windows.png"],
        platformText: "Playstation4, Playstation5, Windows",
        developer: "assets/naughtyDog.png",
        developerText: "Naughty Dog",
        genre: "Action-adventure",
        price: "$14.99",
        release: 2017,
        stars: 4,
        rating: "84%",
        description: "Venturing into India's Western Ghats mountain range, Chloe and Nadine must work together to unearth the artifact and fight their way through to prevent the region from chaos."        
    }
];